---
title: "Additional cfDNA fragment ratio analysis"
author: "Darren Liu"
date: "2024-04-17"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "W:/Shared/LRI/Labs/engclab/LAB_MEMBER_CENTRAL/Darren_Liu/3_cf-DNA")

```

# Load library
```{r libraries}
library(tidyverse)
library(rstatix)
```

# Import
```{r import}

df.ratio <- readRDS("protocol_ms/data/13-fragratio/13-fragratio_summary.rds") # Fragment ratios
df.cor.res <- readRDS("protocol_ms/data/13-fragratio/13-fragratio_corr_summary.rds") # Correlation analysis results

```

# Summarize and combine
```{r summarize}

# Summarize fragment ratio 
df.summary <- df.ratio %>% 
  group_by(id, group2, group3) %>%
  summarise(sd1 = sd(ratio1),
            ratio1 = median(ratio1),
            sd1.corrected = sd(ratio1.corrected),
            ratio1.corrected = median(ratio1.corrected),
            sd2 = sd(ratio2),
            ratio2 = median(ratio2),
            sd2.corrected = sd(ratio2.corrected),
            ratio2.corrected = median(ratio2.corrected),
            sd3 = sd(ratio3),
            ratio3 = median(ratio3),
            sd3.corrected = sd(ratio3.corrected),
            ratio3.corrected = median(ratio3.corrected))

# Merge with df.cor.res
df.cor.res <- df.cor.res %>% select(-group2, -group3) # Remove redundant columns 
df.summary <- df.summary %>%
  inner_join(df.cor.res, by = "id")
  
# Save
write.csv(df.summary, "protocol_ms/data/13-fragratio/13-fragratio_corr_summary240417.csv", row.names = FALSE)
saveRDS(df.summary, "protocol_ms/data/13-fragratio/13-fragratio_corr_summary.rds")
```

# Statistical analysis - KW Test
```{r stat_kw}

# Function for KW test
kw_test <- function(df, group_var, column) {
  formula <- as.formula(paste(column, "~", group_var))
  
  df %>%
    group_by(group = {{group_var}}) %>%
    kruskal_test(formula) %>%
    ungroup()
}

# Function to perform KW test across various columns and combine results
kw_test_multi <- function(df, group) {
  map_dfr(columns, ~ kw_test(df, group, .x)) %>% #map_dfr to row bind results into single df
  arrange(.y.)
}

# Define columns of interest
columns <- setdiff(colnames(df.summary), c("id", "group2", "group3"))

# Perform KW test by subgroups
kw.res.smn <- kw_test_multi(df.summary, "group2") 
kw.res.pre <- kw_test_multi(df.summary, "group3")
kw.res.all <- rbind(kw.res.smn, kw.res.pre) # Combine all 

# Save
write.csv(kw.res.all, "protocol_ms/data/13-fragratio/kwtest_ratio_corr240417.csv", row.names = FALSE)
```

# Statistical Analysis - Wilcoxon Test
```{r stat_wx}

# Function for pairwise Wilcoxon test
pairwise_wilcox_test <- function(df, group_var, column) {
  formula <- as.formula(paste(column, "~", group_var))
  
  df %>%
    group_by(group = {{group_var}}) %>%
    wilcox_test(formula, exact = TRUE) %>%
    adjust_pvalue(method = "BH") %>% # Apply BH correction
    add_significance()
}

pairwise_wilcox_test_multi <- function(df, group) {
  map_dfr(columns, ~ pairwise_wilcox_test(df, group, .x)) %>% 
  arrange(.y.)
}

# Define columns of interest
columns <- setdiff(colnames(df), c("id", "group2", "group3"))

# Perform pairwise Wilcoxon test on subgroups 
wx.res.smn <- pairwise_wilcox_test_multi(df.summary, "group2")
wx.res.pre <- pairwise_wilcox_test_multi(df.summary, "group3")
wx.res.all <- rbind(wx.res.smn, wx.res.pre)

# Save
write.csv(wx.res.all, "protocol_ms/data/13-fragratio/wxtest_ratio_corr240417.csv", row.names = FALSE)
```
